### ISSUE TITLE
dcc-portal: Epics and stories from F2F

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/dcc-portal#3]
https://github.com/ohsu-computational-biology/dcc-portal/wiki/Epics-and-stories-from-Toronto-F2F

@AAMargolin @gitmach@mayfielg @k1643  - can you comment?

**Comment by ghost** [comment]
I reformatted the stories to make them more compact (https://github.com/ohsu-computational-biology/dcc-portal/wiki/DCC-Portal,-ETL-Stories) and sent an email identifying the things I think need to be more specific.  Looks like a good start.

**Comment by bwalsh** [comment]
@k1643 can you make the changes you'd like to see in the document itself?

**Comment by ghost** [comment]
i like the table format, so I could copy the tables to the original doc if you think the table format is acceptable.

**Comment by bwalsh** [comment]
@k1643 The table format is fine - but we should maintain the list of epics, perhaps in its own table.
What I meant by "make the changes you'd like to see" referred to your comments in the email about "I italicized the items I thought needed more detail."  Please go ahead and add/modify that detail
